#!/bin/bash

parseArgs(){
  # sets 4 variables:
  numArgs=1              # the total number of arguments
  arg[0]='Arguments'     # an array of arguments with index matching value[]
  value[0]='Values'      # an array of values with index matching arg[]
  errCount=0             # count of errors detected
  errMsgs=""             # \n seperated list of errors

  # uses
  allowedArgs=(a b help x h e l p)      # Array of allowed arguments
  allowAllArgs=0                        # Allow all arguments and ignore $allowedArgs
                                        # doesn't sound a good idea, but there you go
                                        # export ARGS2ARR_ALL=1 to set on a user basis
  if [ "$ARGS2ARR_ALL" == "1" ]; then allowAllArgs=1; fi

  while [ "$1" != "" ]; do
    if [ "${1:0:1}" == "-" ]; then
      pos="${1%%=*}"
      [[ "$pos" = "$1" ]] && eqpos=255 || eqpos="${#pos}"
      if [ $eqpos -ne 255 ]; then
        if [ "${1:0:2}" != "--" ]; then
          arg[$numArgs]=${1:1:$(( eqpos -1 ))}
          value[$numArgs]=${1:$(( $eqpos + 1 ))}
        else
          arg[$numArgs]=${1:2:$(( eqpos -2 ))}
          value[$numArgs]=${1:$(( $eqpos + 1 ))}
        fi
        shift 1
      elif [ ${1:0:2} != "--" ]; then
        grouplen=$(( ${#1} -1 ))
        for i in $(seq 1 $grouplen);
        do
          arg[$numArgs]=${1:$i:1}
          numArgs=$(( $numArgs + 1 ))
        done
        numArgs=$(( $numArgs - 1 ))
        if [ "${2:0:1}" != "-" ] && [ "$2" != "" ]; then
          value[$numArgs]=$2
          shift 1
        fi
        shift 1
      elif [ "${2:0:1}" != "-" ] && [ "$2" != "" ]; then
        arg[$numArgs]=${1:2}
        value[$numArgs]=$2
        shift 2
      else
        arg[$numArgs]=${1:2}
        shift 1
      fi
    else
      errMsgs=$errMsgs"Unrecognised parameter $1\n"
      numArgs=$(( $numArgs - 1 ))
      errCount=$(( $errCount + 1 ))
      shift 1
    fi
    numArgs=$(( $numArgs + 1 ))
  done
  numArgs=$(( $numArgs - 1 ))

  # Check whether the provided arguments are in $allowedArgs
  if [ $allowAllArgs -ne 1 ]; then
    for i in $(echo ${arg[@]})
    do
      allowed=0
      if [ "$i" == "Arguments" ]; then allowed=1; fi
      for j in $(seq 0 ${#allowedArgs[@]})
      do
        if [ "$i" == "${allowedArgs[$j]}" ]; then
          allowed=1
        fi
      done
      if [ $allowed -eq 0 ]; then
        if [ ${#i} -lt 2 ]; then
          errMsgs=$errMsgs"Invalid parameter '-$i'\n"
        else
          errMsgs=$errMsgs"Invalid parameter '--$i'\n"
        fi
        errCount=$(( $errCount + 1 ))
      fi
    done
  fi

  if [ $errCount -gt 0 ]; then
    errMsgs=${errMsgs::-2}
  fi
}

help(){
cat << EOF

args2arr example
----------------

Converts command line options to 2 'linked' arrays of parameter name
and the value (if any) specified.  Errors are stored as a count and
and as messages; deal with them as you will.

This example shows how to 
 * simply deal with errors
 * create an associative array
 * list  'allowed parameters' found using the associative array
 * check for a single and only parameter


Use
---

Specify an argument (no value):
  -p
  --parameter

Specify a parameter value:
  -p 3
  -p=3
  -p "Long string"
  -p="Long string"
  --parameter 3
  --parameter=3
  -parameter=3
  --parameter "Long string"
  --parameter="Long string"
  -parameter="Long string"

Specify multiple arguments:
  -abc
    is the same as -a -b -c
  -abc 5
    is the same as -a -b -c 5
    or -a -b -c=5
  Note:
  -abc=5
    is not the same and is interpreted as " parameter 'abc' has vale '5' "

Note:
  A parameter *value* starting with "-" must use the '-p=value' format,
  quoted as needed. E.g.  -d=-4 not -d -4

EOF
}

# Call the main function to parse all command line arguments
parseArgs "$@"

# Check if any errors were found
# the function itself won't output anything or exit
if [ $errCount -gt 0 ]; then
  echo $errCount errors found
  echo -e $errMsgs
  exit $errCount
fi

# Combine the 2 arrays into an associative array
# Note: can't be done in the function as 'declare' is needed
# and makes the array local to the function
declare -A argArr
for i in $(seq 1 $numArgs); do
  argArr[${arg[$i]}]=${value[$i]}
done

##########################
# And you're good to go! #
##########################



###########
# Examples

# Report which of the allowed variables are found
for p in ${allowedArgs[@]}; do
  if [ ${argArr[$p]+_} ];then
    if [ "${argArr[$p]}" != "" ]; then
      echo "parameter -$p was found with value ${argArr[$p]}"
    else
      echo "parameter -$p was found";fi
    fi
done

# Display help if --help was provided as first and only parameter
if [ ${argArr[help]+_} ]; then
  if [ "${arg[1]}" == "help" ] && [ ${#@} -eq 1 ]; then
    help
    exit 0
  else
    echo "Help on what?  --help must be first and only parameter"
    exit 1
  fi
fi
